Repository aces/cbrain, pull requests merged in 2018-11, with the labels that each got.

#776 Fix tool creation bug
  BrainPortal/lib/license_agreements.rb
  BrainPortal/spec/models/tool_spec.rb
Labels: Bug, User Interface

#778 Added some console helpers.
  BrainPortal/app/models/application_record.rb
  BrainPortal/config/console_rc/init_rc.rb
  BrainPortal/config/console_rc/lib/admin.rb
Labels: Enhancement

#765 Toolconfig new fields, ux / refactoring to table helper for config/version show and new page and tool show #650
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/app/controllers/tool_configs_controller.rb
  BrainPortal/app/views/bourreaux/show.html.erb
  BrainPortal/app/views/portal/search.html.erb
  BrainPortal/app/views/shared/_show_table_content.html.erb
  BrainPortal/app/views/tool_configs/_by_resource.erb
  BrainPortal/app/views/tool_configs/_by_user.html.erb
  BrainPortal/app/views/tool_configs/_env_key_value_pair.erb
  BrainPortal/app/views/tool_configs/_form_fields.html.erb
  BrainPortal/app/views/tool_configs/_tool_configs_table.html.erb
  BrainPortal/app/views/tool_configs/edit.html.erb
  BrainPortal/app/views/tool_configs/show.html.erb
  BrainPortal/app/views/tools/_form_fields.html.erb
  BrainPortal/app/views/tools/edit.html.erb
  BrainPortal/app/views/tools/new.html.erb
  BrainPortal/config/routes.rb
Labels: Priority: Normal, User Interface
