Repository aces/cbrain, pull requests merged in 2018-02, with the labels that each got.

#705 Load tool_configs before singularity build.
  BrainPortal/app/models/cluster_task.rb
Labels: Bug

#706 Switching project clears the persistent list of userfiles.
  BrainPortal/app/assets/stylesheets/userfiles.css.erb
  BrainPortal/app/controllers/groups_controller.rb
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/app/views/shared/_persistent_selection.html.erb
  BrainPortal/app/views/userfiles/_userfiles_display.html.erb
  BrainPortal/public/javascripts/cbrain/shared/selection_database.js
Labels: Enhancement, User Interface

#708 Last updated indicator refactored. Fix #674
  BrainPortal/app/views/layouts/_section_account.html.erb
  BrainPortal/public/javascripts/cbrain.js
Labels: Priority: Normal, Refactoring, User Interface

#710 Salt reset when changing passwords.
  BrainPortal/app/models/user.rb
Labels: Bug, Security

#715 Plugins can provide a 'lib' directory. Fix #714
  BrainPortal/cbrain_plugins/installed-plugins/lib/.gitignore
  BrainPortal/config/application.rb
  BrainPortal/lib/tasks/cbrain_plugins.rake
Labels: Enhancement, Priority: High

#711 SSH DP collection_index() : fixes #483
  BrainPortal/app/models/ssh_data_provider.rb
Labels: Bug, Priority: Normal

#718 Add container_index_location to permit params for TC.
  BrainPortal/app/controllers/tool_configs_controller.rb
Labels: Bug, Priority: High

#720 Ignore error when building singularity image
  BrainPortal/app/models/cluster_task.rb
Labels: Bug, Enhancement, Singularity

#707 Containers get new mounts for local DPs
  BrainPortal/app/models/cluster_task.rb
Labels: Bug, Docker, Singularity

#712 Better tool config index table. Fix #633
  BrainPortal/app/views/tool_configs/_tool_configs_table.html.erb
Labels: Enhancement, User Interface

#713 Refresh button in task show page near status. Fixes #688
  BrainPortal/app/views/tasks/show.html.erb
Labels: Enhancement, User Interface

#716 Immutable files can't be compressed or uncompressed.
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/file_collection/file_collection.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/single_file/single_file.rb
  BrainPortal/spec/controllers/userfiles_controller_spec.rb
Labels: Bug, Enhancement, Priority: Normal
