Repository aces/cbrain, pull requests merged in 2018-03, with the labels that each got.

#725 Task launch: error when files are not accessible.
  BrainPortal/app/controllers/tasks_controller.rb
Labels: Priority: Normal, User Interface

#723 Misc fixes.
  BrainPortal/app/controllers/data_providers_controller.rb
  BrainPortal/app/helpers/dynamic_form_helper.rb
  BrainPortal/config/console_rc/lib/wirble_hirb_looksee.rb
  BrainPortal/lib/portal_sanity_checks.rb
Labels: Enhancement, Priority: Normal

#727 Fixed Dir.chdir problems with threads. Fix #726
  BrainPortal/app/helpers/select_box_helper.rb
  BrainPortal/app/views/custom_filters/_userfile_custom_filter.html.erb
  BrainPortal/app/views/groups/show.html.erb
  BrainPortal/app/views/invitations/_new.html.erb
  BrainPortal/lib/cbrain_file_revision.rb
Labels: Bug, Priority: High

#734 Fix save preset bug by having belongs to optionnal
  BrainPortal/app/controllers/tasks_controller.rb
  BrainPortal/app/models/cbrain_task.rb
Labels: Bug, Priority: High
