Repository aces/cbrain, pull requests merged in 2018-09, with the labels that each got.

#772 Show table context
  BrainPortal/app/helpers/show_table_helper.rb
  BrainPortal/app/views/access_profiles/show.html.erb
  BrainPortal/app/views/shared/_show_table.html.erb
  BrainPortal/app/views/shared/_show_table_context.html.erb
  BrainPortal/app/views/tasks/show.html.erb
  BrainPortal/config/console_rc/lib/pretty_view.rb
  BrainPortal/config/console_rc/lib/wirble_hirb_looksee.rb
Labels: Enhancement, User Interface

#728 Custom filter refactoring.
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/app/controllers/custom_filters_controller.rb
  BrainPortal/app/helpers/date_range_panel_helper.rb
  BrainPortal/app/models/custom_filter.rb
  BrainPortal/app/models/task_custom_filter.rb
  BrainPortal/app/models/userfile_custom_filter.rb
  BrainPortal/app/views/custom_filters/_custom_filter_li.html.erb
  BrainPortal/app/views/custom_filters/_custom_filter_list.html.erb
  BrainPortal/app/views/custom_filters/_edit.html.erb
  BrainPortal/app/views/custom_filters/_new_task_custom_filter.html.erb
  BrainPortal/app/views/custom_filters/_new_userfile_custom_filter.html.erb
  BrainPortal/app/views/custom_filters/_task_custom_filter.html.erb
  BrainPortal/app/views/custom_filters/_userfile_custom_filter.html.erb
  BrainPortal/app/views/custom_filters/show.html.erb
  BrainPortal/app/views/shared/_date_range_info.html.erb
  BrainPortal/app/views/shared/_date_range_panel.html.erb
  BrainPortal/app/views/userfiles/_filter_items.html.erb
  BrainPortal/config/routes.rb
  BrainPortal/public/javascripts/userfiles.js
  BrainPortal/spec/models/custom_filter_spec.rb
  BrainPortal/spec/models/task_custom_filter_spec.rb
  BrainPortal/spec/models/userfile_custom_filter_spec.rb
Labels: Priority: Normal, Refactoring

#769 Update api
  BrainPortal/app/controllers/users_controller.rb
  BrainPortal/lib/exception_helpers.rb
  BrainPortal/public/swagger/cbrain-5.0.2-swagger.json
  BrainPortal/public/swagger/cbrain-5.0.2-swagger.yaml
Labels: API
