Repository aces/cbrain, pull requests merged in 2019-05, with the labels that each got.

#801 Updated the DataProvider Model and view pages to accommodate new variables for Datalad Dataprovider.
  BrainPortal/app/controllers/data_providers_controller.rb
  BrainPortal/app/views/data_providers/new.html.erb
  BrainPortal/app/views/data_providers/show.html.erb
  BrainPortal/db/migrate/20190322141543_add_datalad_to_data_provider.rb
  BrainPortal/db/schema.rb
Labels: Enhancement, User Interface

#805 A bit of robustness-related code tweaks.
  BrainPortal/app/mailers/cbrain_mailer.rb
  BrainPortal/app/models/remote_resource.rb
  BrainPortal/app/views/custom_filters/_task_custom_filter.html.erb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/csv_file/csv_file.rb
Labels: Bug, Enhancement, Priority: Normal

#806 Boutiques bug. Fixes #794
  BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb
Labels: Enhancement, Priority: Normal

#803 Improvements to rails console, and rdoc generators.
  Bourreau/lib/tasks/bourreau_docs.rake
  BrainPortal/config/console_rc/init_rc.rb
  BrainPortal/config/console_rc/lib/pretty_view.rb
  BrainPortal/config/console_rc/lib/reports.rb
  BrainPortal/lib/tasks/brainportal_docs.rake
Labels: Documentation, Enhancement, Priority: Normal

#802 Fixed task recovery when failure on cluster.
  Bourreau/app/models/bourreau_worker.rb
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/app/models/worker.rb
Labels: Bug, Priority: Normal
