Repository aces/cbrain, pull requests merged in 2019-11, with the labels that each got.

#888 API requests never send or accept cookies.
  BrainPortal/app/controllers/application_controller.rb
  BrainPortal/app/controllers/groups_controller.rb
  BrainPortal/app/controllers/sessions_controller.rb
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/app/models/cbrain_session.rb
  BrainPortal/app/views/layouts/_section_menu.html.erb
  BrainPortal/lib/session_helpers.rb
Labels: API, Bug, Enhancement, Priority: Normal

#890 Prevent updating password with the same password. Fix #886
  BrainPortal/app/models/user.rb
  BrainPortal/spec/models/user_spec.rb
Labels: Enhancement, Priority: Normal, Security, User Interface

#899 Added support for path prefix in S3 Flat DP.
  BrainPortal/app/controllers/data_providers_controller.rb
  BrainPortal/app/models/s3_flat_data_provider.rb
Labels: Enhancement, Priority: High

#901 Fixed QC panel bug
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/app/views/userfiles/quality_control.html.erb
  BrainPortal/public/javascripts/cbrain.js
  BrainPortal/spec/controllers/userfiles_controller_spec.rb
Labels: Bug
