Repository aces/cbrain, pull requests merged in 2019-10, with the labels that each got.

#875 Users now MUST select a destination data provider for their tasks.
  BrainPortal/app/controllers/tasks_controller.rb
  BrainPortal/app/views/tasks/_control.html.erb
  BrainPortal/test_api/req_files/tasks/2-create.in.json
  BrainPortal/test_api/req_files/tasks/2-create.out
Labels: Enhancement, Priority: High, User Interface

#876 Removed site affiliation
  BrainPortal/app/models/remote_resource.rb
  BrainPortal/app/views/bourreaux/_bourreaux_display.html.erb
  BrainPortal/app/views/bourreaux/show.html.erb
  BrainPortal/spec/models/remote_resource_spec.rb
Labels: Priority: Low, Refactoring

#882 Added filtering on resource usage
  BrainPortal/app/controllers/custom_filters_controller.rb
  BrainPortal/app/controllers/portal_controller.rb
  BrainPortal/app/controllers/resource_usage_controller.rb
  BrainPortal/app/models/custom_filter.rb
  BrainPortal/app/models/task_custom_filter.rb
  BrainPortal/app/models/userfile_custom_filter.rb
  BrainPortal/app/views/resource_usage/_resource_usage_table.html.erb
Labels: Priority: Normal, User Interface

#880 Zenodo publishing
  .travis.yml
  BrainPortal/Gemfile
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/app/controllers/resource_usage_controller.rb
  BrainPortal/app/controllers/tasks_controller.rb
  BrainPortal/app/controllers/users_controller.rb
  BrainPortal/app/helpers/zenodo_helper.rb
  BrainPortal/app/models/bourreau.rb
  BrainPortal/app/models/cbrain_task.rb
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/app/models/portal_task.rb
  BrainPortal/app/models/remote_command.rb
  BrainPortal/app/models/site.rb
  BrainPortal/app/models/tool_config.rb
  BrainPortal/app/models/user.rb
  BrainPortal/app/views/resource_usage/_resource_usage_table.html.erb
  BrainPortal/app/views/tasks/_zenodo_deposit_form.html.erb
  BrainPortal/app/views/tasks/show.html.erb
  BrainPortal/app/views/tasks/zenodo.html.erb
  BrainPortal/app/views/userfiles/show.html.erb
  BrainPortal/app/views/users/show.html.erb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/cbrain_task/bash_scriptor/portal/bash_scriptor.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/cbrain_task/diagnostics/portal/diagnostics.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/cbrain_task/parallelizer/bourreau/parallelizer.rb
  BrainPortal/config/routes.rb
  BrainPortal/db/migrate/20191002174842_create_zenodo_attributes.rb
  BrainPortal/db/schema.rb
  BrainPortal/lib/cbrain_task_generators/schema_task_generator.rb
  BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb
  BrainPortal/lib/cbrain_task_generators/templates/portal.rb.erb
  BrainPortal/vendor/cbrain/bin/runtime_info.sh
Labels: Enhancement, Priority: Normal, User Interface

#881 Added CPU time to Network Operation Center
  BrainPortal/app/assets/stylesheets/noc.css
  BrainPortal/app/controllers/noc_controller.rb
  BrainPortal/app/views/noc/dashboard.html.erb
  BrainPortal/config/routes.rb
Labels: Enhancement, User Interface

#883 Added resource usage info to account page.
  BrainPortal/app/helpers/scope_helper.rb
  BrainPortal/app/views/users/show.html.erb
Labels: Priority: Normal, User Interface

#885 Added script_epilogue to ToolConfig objects.
  BrainPortal/app/controllers/tool_configs_controller.rb
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/app/models/tool_config.rb
  BrainPortal/app/views/tool_configs/_form_fields.html.erb
  BrainPortal/app/views/tool_configs/show.html.erb
  BrainPortal/db/migrate/20191023211144_add_script_epilogue_to_tool_config.rb
  BrainPortal/db/schema.rb
Labels: Enhancement, Priority: Normal

#884 Fixed race condition in boutiques outputs
  Bourreau/spec/boutiques/boutiques_tester_spec.rb
  BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb
  BrainPortal/vendor/cbrain/bin/runtime_info.sh
Labels: Boutiques, Bug, Priority: High

#891 Projects
  BrainPortal/app/controllers/groups_controller.rb
  BrainPortal/app/models/system_group.rb
  BrainPortal/app/views/groups/_groups_table.html.erb
Labels: Enhancement, Priority: Normal, User Interface
