Repository aces/cbrain, pull requests merged in 2019-09, with the labels that each got.

#860 Fixes to CSRF check when POST to userfiles download
  BrainPortal/Gemfile
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/db/seeds_test_api.rb
  BrainPortal/lib/api_helpers.rb
  BrainPortal/public/swagger/cbrain-5.1.3-swagger.json
  BrainPortal/public/swagger/cbrain-5.1.3-swagger.yaml
  BrainPortal/test_api/curl_req_tester.pl
  BrainPortal/test_api/lib/parse_req.rb
  BrainPortal/test_api/req_files/userfiles/00-list.out
  BrainPortal/test_api/req_files/userfiles/07-download.out
  BrainPortal/test_api/req_files/userfiles/07b-download_bin.in.json
  BrainPortal/test_api/req_files/userfiles/07b-download_bin.in.rb
  BrainPortal/test_api/req_files/userfiles/07b-download_bin.out
  BrainPortal/test_api/req_files/userfiles/07b-download_bin.req
  Travis/cb_run_tests.sh
  Travis/travis_ci.sh
Labels: API, Bug, Priority: Normal

#840 SSH masters now fail if tunnels can't be opened.
  BrainPortal/app/controllers/custom_filters_controller.rb
  BrainPortal/app/models/userfile.rb
  BrainPortal/lib/ssh_master.rb
Labels: Enhancement, Priority: Normal

#838 Bourreau workers propagate stop to subworkers; fix #741
  Bourreau/app/models/bourreau_worker.rb
Labels: Bug, Priority: Normal

#864 Tool info
  BrainPortal/app/views/tool_configs/_tool_configs_table.html.erb
Labels: Enhancement

#865 Added resource usage tracking.
  Bourreau/app/models/cputime_resource_usage_for_cbrain_task.rb
  Bourreau/app/models/resource_usage.rb
  Bourreau/app/models/space_resource_usage.rb
  Bourreau/app/models/space_resource_usage_for_cbrain_task.rb
  Bourreau/app/models/space_resource_usage_for_userfile.rb
  Bourreau/app/models/time_resource_usage.rb
  Bourreau/app/models/walltime_resource_usage_for_cbrain_task.rb
  BrainPortal/app/controllers/resource_usage_controller.rb
  BrainPortal/app/helpers/resource_usage_helper.rb
  BrainPortal/app/models/cbrain_task.rb
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/app/models/cputime_resource_usage_for_cbrain_task.rb
  BrainPortal/app/models/data_provider.rb
  BrainPortal/app/models/group.rb
  BrainPortal/app/models/remote_resource.rb
  BrainPortal/app/models/resource_usage.rb
  BrainPortal/app/models/space_resource_usage.rb
  BrainPortal/app/models/space_resource_usage_for_cbrain_task.rb
  BrainPortal/app/models/space_resource_usage_for_userfile.rb
  BrainPortal/app/models/time_resource_usage.rb
  BrainPortal/app/models/tool.rb
  BrainPortal/app/models/tool_config.rb
  BrainPortal/app/models/user.rb
  BrainPortal/app/models/userfile.rb
  BrainPortal/app/models/walltime_resource_usage_for_cbrain_task.rb
  BrainPortal/app/views/layouts/_section_account.html.erb
  BrainPortal/app/views/layouts/_section_menu.html.erb
  BrainPortal/app/views/resource_usage/_resource_usage_table.html.erb
  BrainPortal/app/views/resource_usage/index.html.erb
  BrainPortal/app/views/resource_usage/index.js.erb
  BrainPortal/app/views/tasks/_resource_usage.html.erb
  BrainPortal/app/views/tasks/show.html.erb
  BrainPortal/app/views/userfiles/_resource_usage.html.erb
  BrainPortal/app/views/userfiles/show.html.erb
  BrainPortal/config/initializers/inflections.rb
  BrainPortal/config/routes.rb
  BrainPortal/db/migrate/20190913174022_add_resource_usage_table.rb
  BrainPortal/db/schema.rb
  BrainPortal/lib/scir_slurm.rb
  BrainPortal/public/stylesheets/tablesorter_themes/blue/style.css
Labels: Enhancement, Priority: Normal

#869 Added options for busy loops in diagnostics.
  BrainPortal/app/views/tasks/show.html.erb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/cbrain_task/diagnostics/bourreau/diagnostics.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/cbrain_task/diagnostics/portal/diagnostics.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/cbrain_task/diagnostics/views/_task_params.html.erb
Labels: Enhancement, Priority: Normal, User Interface
