Repository aces/cbrain, pull requests merged in 2020-11, with the labels that each got.

#1039 neurohub messaging #986
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/app/assets/stylesheets/neurohub.scss.erb
  BrainPortal/app/controllers/messages_controller.rb
  BrainPortal/app/controllers/neurohub_application_controller.rb
  BrainPortal/app/controllers/nh_messages_controller.rb
  BrainPortal/app/models/count_resource_usage_for_user_message.rb
  BrainPortal/app/models/message.rb
  BrainPortal/app/views/layouts/_neurohub_flash_message.html.erb
  BrainPortal/app/views/layouts/_neurohub_navbar.html.erb
  BrainPortal/app/views/layouts/_neurohub_secondary_navbar.html.erb
  BrainPortal/app/views/messages/_message_details.html.erb
  BrainPortal/app/views/messages/_message_table_row.html.erb
  BrainPortal/app/views/nh_invitations/_message_details.html.erb
  BrainPortal/app/views/nh_messages/index.html.erb
  BrainPortal/app/views/nh_messages/new.html.erb
  BrainPortal/config/routes.rb
  BrainPortal/lib/neurohub_helpers.rb
Labels: Enhancement, NeuroHub

#1050 [FIX] for optional output file in Boutiques
  BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb
Labels: Boutiques, Bug, Priority: High

#1052 Arbitrary container options for singularity exec command
  BrainPortal/app/controllers/tool_configs_controller.rb
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/app/views/tool_configs/_form_fields.html.erb
  BrainPortal/db/migrate/20201105184731_add_container_params_to_tool_config.rb
  BrainPortal/db/schema.rb
Labels: Enhancement, Priority: Normal, Singularity, User Interface
