Repository aces/cbrain, pull requests merged in 2020-12, with the labels that each got.

#1061 save short orcids fixes #1060
  BrainPortal/app/controllers/nh_sessions_controller.rb
  BrainPortal/app/controllers/nh_users_controller.rb
  BrainPortal/app/views/nh_sessions/new.html.erb
  BrainPortal/app/views/nh_users/_form.html.erb
  BrainPortal/app/views/nh_users/show.html.erb
  BrainPortal/lib/neurohub_helpers.rb
Labels: Bug, NeuroHub, Priority: High

#1064 [FIX] renamimg output of Boutiques tasks
  BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb
Labels: Bug

#1059 Tool config data immutability flag resolves #1054
  BrainPortal/app/controllers/tasks_controller.rb
  BrainPortal/app/controllers/tool_configs_controller.rb
  BrainPortal/app/views/tool_configs/_form_fields.html.erb
  BrainPortal/db/migrate/20201123133913_add_inputs_readonly_to_tool_config.rb
  BrainPortal/db/schema.rb
  BrainPortal/lib/cbrain_task_generators/templates/portal.rb.erb
  BrainPortal/spec/boutiques/boutiques_tester_spec.rb
Labels: Enhancement, Priority: High
