Repository aces/cbrain, pull requests merged in 2020-01, with the labels that each got.

#912 Fix for input without key-value in Boutiques descriptor
  BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb
Labels: Boutiques, Bug

#913 Fix DP report
  BrainPortal/app/views/data_providers/_dp_report_table.html.erb
Labels: Bug

#916 Improved dashboard
  BrainPortal/app/controllers/noc_controller.rb
  BrainPortal/app/models/message.rb
  BrainPortal/app/views/noc/dashboard.html.erb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/mp4_video_file/views/_html5_mp4_video.html.erb
Labels: Priority: Normal, User Interface
