Repository aces/cbrain, pull requests merged in 2020-10, with the labels that each got.

#1034 [ADD] name of the container image (tc show page)
  BrainPortal/app/controllers/tool_configs_controller.rb
  BrainPortal/app/views/tool_configs/_form_fields.html.erb
Labels: Enhancement, User Interface

#1047 Launch task div
  BrainPortal/public/javascripts/cbrain/userfiles/launch_task.js
  BrainPortal/public/javascripts/userfiles.js
Labels: Enhancement

#1042 Empty invite fix #1038
  BrainPortal/app/controllers/invitations_controller.rb
Labels: Bug, User Interface
