Repository aces/cbrain, pull requests merged in 2021-05, with the labels that each got.

#1120 Added list of all tools and datasets.
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/app/controllers/portal_controller.rb
  BrainPortal/app/views/portal/_available_datasets_table.html.erb
  BrainPortal/app/views/portal/_available_tools_table.html.erb
  BrainPortal/app/views/portal/available.html.erb
  BrainPortal/app/views/portal/welcome.html.erb
  BrainPortal/app/views/sessions/new.html.erb
  BrainPortal/config/routes.rb
Labels: Documentation, Priority: Normal, User Interface

#1116 keep hbhl always abbreviated in logos #1112
  BrainPortal/app/assets/styleguide/NH_LOGO.jpg
  BrainPortal/app/assets/stylesheets/neurohub.scss.erb
  BrainPortal/public/images/neurohub/NH_hbhl_wordmark_RGB.png
  BrainPortal/public/images/neurohub/NH_hbhl_wordmark_black.png
  BrainPortal/public/images/neurohub/NH_hbhl_wordmark_grayscale.png
  BrainPortal/public/images/neurohub/NH_hbhl_wordmark_white.png
Labels: Enhancement, NeuroHub, User Interface

#1117 correct a flash css defect fixes #1062
  BrainPortal/app/assets/stylesheets/neurohub.scss.erb
Labels: Bug, Priority: Normal, User Interface

#1110 keep select 'chosenified' after ajax fixes #1098
  BrainPortal/public/javascripts/cbrain.js
Labels: Bug, User Interface

#1111 Cbcsv could have different extensions fixes #1063
  BrainPortal/lib/cbrain_task_generators/templates/portal.rb.erb
Labels: Boutiques, Bug

#1121 Added CSP headers for stream() action.
  BrainPortal/app/controllers/userfiles_controller.rb
Labels: Enhancement, Priority: High, Security, User Interface
