Repository aces/cbrain, pull requests merged in 2021-09, with the labels that each got.

#1155 Fix for optional list in task params
  BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
Labels: Bug

#1152 boutiques parameter line breaks
  BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
Labels: Boutiques

#1157 Added 'Login With Globus' on NH main page
  BrainPortal/app/assets/stylesheets/neurohub.scss.erb
  BrainPortal/app/controllers/nh_sessions_controller.rb
  BrainPortal/app/controllers/nh_users_controller.rb
  BrainPortal/app/controllers/sessions_controller.rb
  BrainPortal/app/controllers/users_controller.rb
  BrainPortal/app/views/nh_sessions/new.html.erb
  BrainPortal/app/views/nh_users/_form.html.erb
  BrainPortal/app/views/nh_users/show.html.erb
  BrainPortal/config/routes.rb
  BrainPortal/lib/globus_helpers.rb
Labels: Enhancement, User Interface, Priority: Normal, Security, NeuroHub
