Repository aces/cbrain, pull requests merged in 2021-11, with the labels that each got.

#1169 [RM] unused function
  BrainPortal/app/controllers/signups_controller.rb
Labels: Refactoring

#1148 Individual download
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/file_collection/views/_directory_contents.html.erb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/file_collection/views/_file_collection_top_table.html.erb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/file_collection/views/_plain_file_list_row.html.erb
Labels: Enhancement, Priority: Normal

#1171 [FIX] Display NOC even if the portal is locked
  BrainPortal/app/controllers/noc_controller.rb
Labels: Enhancement

#1137 let's add 'all-or-none' boutiques group parameter validation? #1136
  BrainPortal/app/models/boutiques_portal_task.rb
  BrainPortal/lib/cbrain_task_generators/templates/portal.rb.erb
Labels: Boutiques

#1170 [FIX] tool_config creation for Boutiques with Docker image
  BrainPortal/app/models/tool_config.rb
  BrainPortal/lib/cbrain_task_generators/schema_task_generator.rb
Labels: Enhancement, Singularity

#1160 Institution section of signup
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/app/views/nh_signups/new.html.erb
  BrainPortal/app/views/signups/new.html.erb
Labels: User Interface

#1177 Adds the user's private UserGroup in NH
  BrainPortal/app/assets/stylesheets/neurohub.scss.erb
  BrainPortal/app/controllers/nh_invitations_controller.rb
  BrainPortal/app/controllers/nh_projects_controller.rb
  BrainPortal/app/views/nh_projects/_projects_table.html.erb
  BrainPortal/app/views/nh_projects/index.html.erb
  BrainPortal/app/views/nh_projects/show.html.erb
  BrainPortal/lib/neurohub_helpers.rb
Labels: Enhancement, User Interface, NeuroHub

#1172 [FIX] access profile's log when update a user
  BrainPortal/app/controllers/users_controller.rb
Labels: Enhancement
