Repository aces/cbrain, pull requests merged in 2021-01, with the labels that each got.

#1080 allow create new task without any toolconfig fix #1078
  BrainPortal/app/controllers/tasks_controller.rb
Labels: Bug

#1079 New GitHub actions CI
  .github/workflows/cbrain_ci.yaml
  .github/workflows/scripts/make_cbrain_app_name_rb.sh
  .github/workflows/scripts/make_database_yml.sh
  .travis.yml.old
  README.md
Labels: API, Enhancement, Priority: High, Testing

#1073 [FIX] api_request when request came from jQuery
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/lib/api_helpers.rb
Labels: Bug

#1083 more uniform csv quotes (more quotes) fixes #1082
  BrainPortal/app/views/userfiles/index.csv.erb
Labels: Enhancement, User Interface
