Repository aces/cbrain, pull requests merged in 2021-02, with the labels that each got.

#1084 no default targeting to readonly active aka current groups #1055
  BrainPortal/app/controllers/bourreaux_controller.rb
  BrainPortal/app/controllers/data_providers_controller.rb
  BrainPortal/app/controllers/tasks_controller.rb
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/app/views/userfiles/_dialogs.html.erb
  BrainPortal/lib/session_helpers.rb
  BrainPortal/spec/controllers/userfiles_controller_spec.rb
Labels: Bug, Priority: High, Security, User Interface

#1086 Update bourreau.rb.erb
  BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb
Labels: Boutiques, Bug, Priority: High

#1089 the master_select boxes in the browse provider page no longer work
  BrainPortal/public/javascripts/cbrain.js
Labels: Bug, User Interface

#1091 Tag
  BrainPortal/lib/cbrain_file_revision.rb
  BrainPortal/script/show_cbrain_rev
Labels: Refactoring

#1095 New hide_filtered() method
  BrainPortal/app/models/exception_log.rb
  BrainPortal/app/models/message.rb
  BrainPortal/lib/cbrain_extensions/hash_extensions/conversions.rb
Labels: Rails, Refactoring

#1096 bump z-index of data provider type info box fixes #1093
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
Labels: Bug, User Interface
