Repository aces/cbrain, pull requests merged in 2022-03, with the labels that each got.

#1206 Cookie notification, crude version for review
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/app/assets/stylesheets/neurohub.scss.erb
  BrainPortal/app/views/layouts/_cbrain_application.html.erb
  BrainPortal/app/views/layouts/_neurohub_application.html.erb
  BrainPortal/app/views/layouts/_section_cookie_notif.html.erb
Labels: Enhancement, Question, User Interface, Priority: High

#1212 Small view changes.
  BrainPortal/app/controllers/portal_controller.rb
  BrainPortal/app/helpers/resource_link_helper.rb
  BrainPortal/app/models/application_record.rb
  BrainPortal/app/views/data_providers/_dp_browse_table.html.erb
Labels: User Interface, Priority: Normal, Admin

#1211 Run numbers only increase at startup restart
  Bourreau/app/models/bourreau_worker.rb
Labels: Bug, Enhancement, Refactoring, Priority: Normal

#1213 Added a auth_method 'keyboard-interactive' to SFTP
  BrainPortal/app/models/en_cbrain_ssh_data_provider.rb
  BrainPortal/app/models/ssh_data_provider_base.rb
  BrainPortal/app/models/userkey_flat_dir_ssh_data_provider.rb
Labels: Bug, Priority: Normal, Security, Admin

#1210 Adds a new rake task cbrain:models:broken
  BrainPortal/lib/tasks/clean_broken_associations.rake
Labels: Enhancement, Priority: Normal, Admin

#1216 Improvements on boutiques input cache cleaner.
  BrainPortal/lib/boutiques_input_cache_cleaner.rb
Labels: Enhancement, Priority: High, Boutiques

#1218 New Boutiques module for cleaning output caches
  Bourreau/lib/boutiques_output_cache_cleaner.rb
  BrainPortal/app/models/boutiques_portal_task.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/cbrain_task/boutiques_task/views/_show_params.html.erb
  BrainPortal/lib/boutiques_output_cache_cleaner.rb
Labels: Enhancement, Priority: High, Boutiques

#1208 [FIX] Userfiles error display
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/file_collection/file_collection.rb
  BrainPortal/spec/models/file_collection_spec.rb
Labels: Bug

#1215 [REFACTORING] of size condition for has_viewer
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/csv_file/csv_file.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/single_file/single_file.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/text_file/text_file.rb
Labels: Enhancement, Refactoring, Priority: Normal

#1219 Disk Quota System
  Bourreau/app/models/disk_quota.rb
  Bourreau/lib/cbrain_disk_quota_exceeded.rb
  BrainPortal/app/controllers/disk_quotas_controller.rb
  BrainPortal/app/models/disk_quota.rb
  BrainPortal/app/models/userfile.rb
  BrainPortal/app/views/data_providers/_data_providers_table.html.erb
  BrainPortal/app/views/disk_quotas/_disk_quotas_table.html.erb
  BrainPortal/app/views/disk_quotas/index.html.erb
  BrainPortal/app/views/disk_quotas/index.js.erb
  BrainPortal/app/views/disk_quotas/show.html.erb
  BrainPortal/app/views/layouts/_section_account.html.erb
  BrainPortal/app/views/layouts/_section_menu.html.erb
  BrainPortal/config/console_rc/lib/pretty_view.rb
  BrainPortal/config/console_rc/lib/reports.rb
  BrainPortal/config/console_rc/lib/wirble_hirb_looksee.rb
  BrainPortal/config/initializers/inflections.rb
  BrainPortal/config/routes.rb
  BrainPortal/db/migrate/20220315153324_add_disk_quotas.rb
  BrainPortal/db/schema.rb
  BrainPortal/lib/cbrain_disk_quota_exceeded.rb
Labels: User Interface, Priority: Normal, Admin

#1223 Data Tracking Framework.
  Bourreau/app/models/data_usage.rb
  BrainPortal/app/controllers/groups_controller.rb
  BrainPortal/app/controllers/portal_controller.rb
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/app/models/data_usage.rb
  BrainPortal/app/views/groups/new.html.erb
  BrainPortal/app/views/groups/show.html.erb
  BrainPortal/app/views/portal/report.html.erb
  BrainPortal/app/views/userfiles/show.html.erb
  BrainPortal/config/console_rc/lib/pretty_view.rb
  BrainPortal/config/console_rc/lib/wirble_hirb_looksee.rb
  BrainPortal/db/migrate/20220324155533_add_group_data_tracking_table.rb
  BrainPortal/db/schema.rb
Labels: Enhancement, User Interface, Priority: Normal, Admin
