Repository aces/cbrain, pull requests merged in 2022-04, with the labels that each got.

#1230 [ADD] method to generate fake files list for FileCollection
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/file_collection/file_collection.rb
Labels: Enhancement

#1228 Admins can now provide dashboard messages
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/app/assets/stylesheets/neurohub.scss.erb
  BrainPortal/app/controllers/application_controller.rb
  BrainPortal/app/controllers/messages_controller.rb
  BrainPortal/app/controllers/neurohub_portal_controller.rb
  BrainPortal/app/controllers/portal_controller.rb
  BrainPortal/app/views/messages/_message_details.html.erb
  BrainPortal/app/views/messages/new.html.erb
  BrainPortal/app/views/messages/new_dashboard.html.erb
  BrainPortal/app/views/neurohub_portal/welcome.html.erb
  BrainPortal/app/views/portal/welcome.html.erb
  BrainPortal/db/migrate/20220418144014_add_neurohub_portal_dashboard_messages.rb
  BrainPortal/db/schema.rb
Labels: Enhancement, User Interface, Priority: Normal, Admin

#1229 Portal and Bourreau communicate over tunnelled UNIX domain sockets
  Bourreau/config/puma.rb
  Bourreau/config/secrets.yml
  Bourreau/script/cbrain_bashrc
  Bourreau/script/cbrain_remote_ctl
  Bourreau/script/cbrain_remote_ctl_rb
  Bourreau/script/puma_wait_wrapper
  Bourreau/script/watcher
  BrainPortal/app/controllers/bourreaux_controller.rb
  BrainPortal/app/controllers/controls_controller.rb
  BrainPortal/app/models/bourreau.rb
  BrainPortal/app/models/remote_resource.rb
  BrainPortal/app/views/bourreaux/_bourreaux_display.html.erb
  BrainPortal/app/views/bourreaux/new.html.erb
  BrainPortal/app/views/bourreaux/show.html.erb
  BrainPortal/config/console_rc/lib/pretty_view.rb
  BrainPortal/config/locales/en.yml
  BrainPortal/db/schema.rb
  BrainPortal/db/seeds_dev.rb
  BrainPortal/db/seeds_test_api.rb
  BrainPortal/db/seeds_test_bourreau.rb
  BrainPortal/lib/ssh_master.rb
  BrainPortal/spec/models/bourreau_spec.rb
  BrainPortal/spec/models/remote_resource_spec.rb
Labels: Enhancement, Refactoring, Installation, Priority: High, Security, Rails, Admin
