Repository aces/cbrain, pull requests merged in 2022-06, with the labels that each got.

#1243 Improve the `select_all` mechanism
  BrainPortal/app/helpers/dynamic_form_helper.rb
  BrainPortal/public/javascripts/cbrain.js
Labels: Enhancement, User Interface

#1242 Added API endpoint to get a TC's descriptor
  BrainPortal/app/controllers/tool_configs_controller.rb
  BrainPortal/app/views/tool_configs/_tool_configs_table.html.erb
  BrainPortal/app/views/tool_configs/boutiques_descriptor.html.erb
  BrainPortal/config/routes.rb
Labels: Enhancement, User Interface, Priority: Normal, API, Boutiques

#1239 Improved cbrain_remote_ctl
  Bourreau/config/puma.rb
  Bourreau/script/cbrain_remote_ctl
  Bourreau/script/watcher
  BrainPortal/app/models/bourreau.rb
Labels: Enhancement, Installation, Priority: Normal, Rails
