Repository aces/cbrain, pull requests merged in 2023-03, with the labels that each got.

#1310 [ADD] BoutiquesCollectionBasenamesListMaker module.
  Bourreau/lib/boutiques_collection_basenames_list_maker.rb
  BrainPortal/lib/boutiques_collection_basenames_list_maker.rb
Labels: Priority: Normal, Boutiques

#1313 Added SquashifierEnCbrainSshDataProvider class
  Bourreau/app/models/squashifier_en_cbrain_ssh_data_provider.rb
  BrainPortal/app/models/squashifier_en_cbrain_ssh_data_provider.rb
Labels: Enhancement, Priority: Normal, Admin

#1314 Adjusted filters for sdterr messages of SSH
  BrainPortal/app/models/sing_bindmount_data_provider.rb
  BrainPortal/app/models/sing_squashfs_data_provider.rb
  BrainPortal/app/models/squashifier_en_cbrain_ssh_data_provider.rb
  BrainPortal/app/models/ssh_data_provider.rb
  BrainPortal/app/models/ssh_data_provider_base.rb
Labels: Bug, Priority: High
