Repository aces/cbrain, pull requests merged in 2023-02, with the labels that each got.

#1258 Prefetch tasks git file revision info resolves #1248
  Bourreau/lib/bourreau_system_checks.rb
Labels: Enhancement, Boutiques

#1277 Load description when use preset of a task
  BrainPortal/app/controllers/tasks_controller.rb
Labels: Enhancement

#1300 Ext3 capturing of files in cbrain tasks
  Bourreau/lib/boutiques_ext3_capturer.rb
  BrainPortal/app/models/boutiques_cluster_task.rb
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/app/models/tool_config.rb
  BrainPortal/app/views/tool_configs/_form_fields.html.erb
  BrainPortal/lib/boutiques_ext3_capturer.rb
  BrainPortal/lib/boutiques_support.rb
  BrainPortal/lib/cbrain_extensions/hash_extensions/conversions.rb
Labels: Priority: High, Admin

#1304 Updating the list of users in a workgroup (Bug1+Bug2)
  BrainPortal/app/helpers/dynamic_form_helper.rb
  BrainPortal/public/javascripts/cbrain.js
Labels: Bug

#1276 Boutiques modules integrator information
  BrainPortal/app/models/boutiques_portal_task.rb
Labels: Enhancement, Boutiques

#1305 Add BoutiquesSaveStdOutStdErr module to save stderr and/or sdtout
  Bourreau/lib/boutiques_save_std_out_std_err.rb
  BrainPortal/lib/boutiques_save_std_out_std_err.rb
Labels: Enhancement, Boutiques
