Repository aces/cbrain, pull requests merged in 2024-02, with the labels that each got.

#1370 Data provider column for task table #1368
  BrainPortal/app/helpers/scope_helper.rb
  BrainPortal/app/views/tasks/_tasks_display.html.erb
Labels: User Interface

#1377 [ADD] switch user via API
  BrainPortal/app/controllers/users_controller.rb
  BrainPortal/config/routes.rb
Labels: Enhancement, Priority: High

#1379 [FIX] Copying file issue
  BrainPortal/app/models/data_provider.rb
Labels: Bug, Priority: High

#1380 [ADD] ssh key to /user/id
  BrainPortal/app/controllers/users_controller.rb
  BrainPortal/test_api/req_files/users/sequence/0-adminget.out
  BrainPortal/test_api/req_files/users/sequence/2-normget.out
Labels: Priority: High, API

#1372 Added remote resource 'copy files' operation
  BrainPortal/app/models/remote_command.rb
  BrainPortal/app/models/remote_resource.rb
Labels: Enhancement, Priority: Normal, Admin
