Repository aces/cbrain, pull requests merged in 2025-01, with the labels that each got.

#1455 Add pagination to the BackgroundActivity index page #1450
  BrainPortal/app/controllers/background_activities_controller.rb
  BrainPortal/app/views/background_activities/_background_activity_table.html.erb
Labels: User Interface, API

#1452 [ADD] Boutiques lib to copy an input before running the cmd line
  Bourreau/lib/boutiques_input_copier.rb
  BrainPortal/lib/boutiques_input_copier.rb
Labels: Boutiques

#1460 Final removal of RawData module
  BrainPortal/app/views/tasks/_tasks_display.html.erb
  BrainPortal/app/views/userfiles/_quality_control_panel.html.erb
  BrainPortal/app/views/users/_users_table.html.erb
  BrainPortal/config/initializers/added_core_extensions/active_record.rb
  BrainPortal/lib/cbrain_extensions/active_record_extensions/relation_extensions/raw_data.rb
  BrainPortal/lib/tasks/cbrain_plugins.rake
Labels: Refactoring

#1453 [bugfix] block download files of undetermined (yet) size #1447
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/spec/controllers/userfiles_controller_spec.rb
Labels: Bug

#1451 File name verifier
  Bourreau/lib/boutiques_file_name_verifier.rb
  BrainPortal/lib/boutiques_file_name_verifier.rb
Labels: Boutiques

#1443 Error codes support in boutiques
  BrainPortal/app/models/boutiques_cluster_task.rb
Labels: Boutiques

#1429 Incomplete plugins list in About Us page #1427
  BrainPortal/app/views/portal/about_us.html.erb
Labels: User Interface

#1424 remove file copy endpoint #1413
  BrainPortal/app/controllers/bourreaux_controller.rb
  BrainPortal/app/models/remote_command.rb
  BrainPortal/app/models/remote_resource.rb
  BrainPortal/config/routes.rb
Labels: Refactoring, API, Admin
