Repository aces/cbrain, pull requests merged in 2025-08, with the labels that each got.

#1541 [FIX] show_table render when re-render the form with a subclass
  BrainPortal/app/helpers/show_table_helper.rb
Labels: Bug

#1543 Bb
  BrainPortal/app/views/userfiles/quality_control.html.erb
Labels: User Interface, Priority: Normal

#1532 New optional 'reverse ssh' service configuration.
  Bourreau/script/cbrain_remote_ctl
  Bourreau/script/cbrain_reverse_ssh
  Bourreau/script/watcher
  BrainPortal/app/controllers/bourreaux_controller.rb
  BrainPortal/app/models/background_activity/copy_file.rb
  BrainPortal/app/models/bourreau.rb
  BrainPortal/app/models/remote_resource.rb
  BrainPortal/app/views/bourreaux/_bourreaux_display.html.erb
  BrainPortal/app/views/bourreaux/show.html.erb
  BrainPortal/db/migrate/20250617184048_add_reverse_network_params_to_remote_resource.rb
  BrainPortal/db/schema.rb
  BrainPortal/lib/ssh_master.rb
  BrainPortal/spec/models/remote_resource_spec.rb
Labels: Enhancement, Refactoring, Priority: High, Admin
