Repository aces/cbrain, pull requests merged in 2025-03, with the labels that each got.

#1449 Overlay in available page
  BrainPortal/app/helpers/rich_ui_helper.rb
  BrainPortal/app/views/portal/_available_datasets_table.html.erb
  BrainPortal/app/views/portal/_available_tools_table.html.erb
  BrainPortal/app/views/portal/available.html.erb
  BrainPortal/public/javascripts/cbrain.js
Labels: User Interface

#1478 Overlay in available page (#1449)
  BrainPortal/app/helpers/rich_ui_helper.rb
  BrainPortal/app/views/portal/_available_datasets_table.html.erb
  BrainPortal/app/views/portal/_available_tools_table.html.erb
  BrainPortal/app/views/portal/available.html.erb
  BrainPortal/public/javascripts/cbrain.js
Labels: User Interface, Priority: Normal

#1475 allow autolink group description
  BrainPortal/app/controllers/groups_controller.rb
  BrainPortal/app/helpers/rich_ui_helper.rb
  BrainPortal/app/views/groups/show.html.erb
Labels: User Interface, Admin

#1479 refactor: remove submit_subtasks_from_json
  Bourreau/app/models/bourreau_worker.rb
  BrainPortal/app/models/cluster_task.rb
Labels: Refactoring, Priority: Normal

#1473 bugfix : Destroying a user might leave behinds their WorkGroups #1431
  BrainPortal/app/models/user.rb
Labels: Admin

#1407 CBRAIN should not change data provider type arbitrary (in presence of missed or incorrect fields)
  BrainPortal/app/views/data_providers/new.html.erb
Labels: Bug, User Interface, Priority: Normal

#1466 improving log_params_changes() for boutiques tasks #1465
  BrainPortal/app/models/boutiques_portal_task.rb
  BrainPortal/app/models/cbrain_task.rb
  BrainPortal/spec/models/cbrain_task_spec.rb
Labels: Enhancement, Boutiques

#1428 Use a dedicated helper to check current controller action in views #1425
  BrainPortal/app/views/data_providers/new.html.erb
  BrainPortal/app/views/layouts/_neurohub_navbar.html.erb
  BrainPortal/app/views/layouts/_neurohub_secondary_navbar.html.erb
  BrainPortal/app/views/layouts/_section_cookie_notif.html.erb
  BrainPortal/app/views/layouts/_section_main.html.erb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/text_file/views/_text_file.html.erb
Labels: User Interface, Refactoring, NeuroHub

#1420 Increase visibility of the full tool list link #1409
  BrainPortal/app/controllers/portal_controller.rb
  BrainPortal/app/views/portal/welcome.html.erb
Labels: User Interface

#1401 Optimise task binding of local provider folders
  BrainPortal/app/models/boutiques_cluster_task.rb
  BrainPortal/app/models/boutiques_portal_task.rb
  BrainPortal/app/models/cbrain_task.rb
  BrainPortal/app/models/cluster_task.rb
Labels: Enhancement, Boutiques

#1423 Add admin option to enable/disable compression when archiving tasks #1123
  BrainPortal/app/controllers/tasks_controller.rb
  BrainPortal/app/models/background_activity/archive_task_workdir.rb
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/app/views/tasks/_task_menu.html.erb
Labels: Enhancement, Admin

#1331 fix error message duplication for duplicate filename ( fixes #1309 )
  BrainPortal/app/controllers/userfiles_controller.rb
  BrainPortal/public/javascripts/cbrain.js
Labels: User Interface, Priority: Low

#1392 Log overlay in task
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/app/models/tool_config.rb
Labels: Bug, Enhancement, User Interface

#1333 [ADD] ability to add note at the top of form when creating a task
  BrainPortal/cbrain_plugins/cbrain-plugins-base/cbrain_task/boutiques_task/views/_task_params.html.erb
Labels: Enhancement, Boutiques

#1356 logging walltime and other qsub details
  BrainPortal/app/models/cluster_task.rb
Labels: Enhancement, Admin

#1348 utility module make folders #1343
  Bourreau/lib/boutiques_dir_maker.rb
  BrainPortal/lib/boutiques_dir_maker.rb
Labels: Enhancement, Boutiques, Admin

#1488 Adjust Tool count
  BrainPortal/app/controllers/portal_controller.rb
  BrainPortal/app/views/portal/welcome.html.erb
Labels: User Interface

#1487 Added touch command for some persistent files
  Bourreau/lib/bourreau_system_checks.rb
  BrainPortal/lib/cbrain_system_checks.rb
Labels: Enhancement, Admin

#1354 HTML model and viewer plugin
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/html_file.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
Labels: User Interface, Priority: High, Security
