Repository aces/cbrain, pull requests merged in 2025-04, with the labels that each got.

#1489 Improved task deletion
  BrainPortal/app/controllers/tasks_controller.rb
  BrainPortal/app/models/background_activity/destroy_task_without_workdir.rb
  BrainPortal/test_api/req_files/tasks/4-destroy.out
Labels: Enhancement, Admin

#1493 remove redundant HTML pass through code resolves #1490
  BrainPortal/app/helpers/userfiles_helper.rb
  BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
Labels: Refactoring

#1346 a button to copy api token to clipboard #1345
  BrainPortal/app/assets/stylesheets/cbrain.css.erb
  BrainPortal/app/helpers/basic_helper.rb
  BrainPortal/app/helpers/rich_ui_helper.rb
  BrainPortal/app/views/users/new_token.html.erb
  BrainPortal/public/javascripts/cbrain.js
Labels: User Interface, API

#1485 Refactor message handling to use invitation_group_id
  BrainPortal/app/controllers/invitations_controller.rb
  BrainPortal/app/controllers/nh_invitations_controller.rb
  BrainPortal/app/models/invitation.rb
  BrainPortal/app/models/message.rb
  BrainPortal/app/views/groups/show.html.erb
  BrainPortal/db/migrate/20250324164153_rename_message_group_id_to_invitation_group_id.rb
  BrainPortal/db/schema.rb
Labels: Refactoring, Priority: Normal

#1504 BTQ tasks can propagate number of cores to Scir
  BrainPortal/app/models/boutiques_cluster_task.rb
  BrainPortal/app/models/cluster_task.rb
  BrainPortal/lib/scir.rb
  BrainPortal/lib/scir_slurm.rb
Labels: Enhancement, Boutiques, Admin
